### ISSUE TITLE
Decrease memory usage

### ISSUE THREAD

**Issue by carlomazzaferro** [carlomazzaferro/scikit-hts#1]
A single Prophet model fit on a fairly small dataset generates a model of aaround 2GB: https://gist.github.com/carlomazzaferro/41c13d73067c08f9a7c2f5b148eccbe0

When performing fits on hundreds of models this become a bottleneck, as each of the models is kept in memory, as they need to be available during the prediction step.

Proposed solutions:
1. Limit the behavior of `FBProphetModel` to implement only `fit_predict`, removing the need to keep models in memory
2. For each time series, fit and serialize the model, keeping in memory only a reference to the model's serialized path. On predict, load each model one by one

**Comment by carlomazzaferro** [comment]
Fixed: https://github.com/carlomazzaferro/scikit-hts/commit/12ccbbeb57acc103e6d1f9ec0ae06a21541bfce8

Not an issue for other models, as memory consumptions is low. Might re-open if it becomes an issue for more complex models, i.e. SARIMAX with multiple exogenous variables

**Comment by aakashparsi** [comment]
Hey @carlomazzaferro, As you stated above I'm facing the memory issue for the SARIMAX even though if I'm using low_memory = True. Any quick fixes?
