### ISSUE TITLE
[BUG] Prediction broken with KeyError: "Invalid unit abbreviation: QS-OCT"

### ISSUE THREAD

**Issue by vtoliveira** [carlomazzaferro/scikit-hts#14]
**Describe the bug**
After fitting a model using HTSRegressor when calling predict method there is an error coming from pandas timedelta functionality, apparently pandas.Timedelta does not accept quarterly frequency indexes.

![image](https://user-images.githubusercontent.com/32197310/78465926-ed516b80-76d1-11ea-8a8b-42c8bd12e87a.png)

**To Reproduce**
I used visnights data got from Hyndman book, I can actually upload the notebook for you in scikit-examples so we can further investigate that.

**Expected behavior**
My last date was:
```python
self.nodes.item.index.max()
Out: Timestamp('2016-10-01 00:00:00', freq='QS-JAN')
```
And expected output was:
```python
DatetimeIndex(['2017-01-01', '2017-04-01', '2017-07-01', '2017-10-01',
               '2018-01-01'],
              dtype='datetime64[ns]', freq='QS-JAN')
```
for steps_ahead = 4.

**Desktop (please complete the following information):**
 - OS: WSL
 - scikit-hts version: 0.5.0
- Python version: 3.7.4

**Additional context**

I did a google research, and the problem is that pandas.Timedelta does not accept Quarterly frequencies, and not even monthly / yearly ones, that could be a problem.

**Comment by vtoliveira** [comment]
Using pandas.Period might solve the problem, I need to investigate more, but you can give a look:

```python
period = pd.Period(value=clf.nodes.item.index.max(), freq="Q") + 2
Out: Period('2017Q2', 'Q-DEC')

period + 2
period.to_timestamp()
Out: Timestamp('2017-04-01 00:00:00')
```

The problem is that QS-JAN should be converted to Q or Q-DEC in this case.

**Comment by vtoliveira** [comment]
I give a try using only period parameter for pandas.date_range, like this:

```python
future = pandas.date_range(freq=freq,
                           start=self.nodes.item.index.max(),
                           periods=steps_ahead
                           )
```

It worked without errors, is this helpful?

**Comment by carlomazzaferro** [comment]
I'm absolutely in favour of statsmodel's implementation. Mine was something I came up with and truthfully it is not too thoroughly tested. I can look into it this weekend, but your contribution is welcome as well.

**Comment by vtoliveira** [comment]
So, this seems to be a simple modification, I will work on that and write some tests. I will look that kind of tests they do in statsmodels as well. Have you implemented any frequency check test?
