### ISSUE TITLE
Does HTS handle linear regression in a forecast?

### ISSUE THREAD

**Issue by vasuki1982** [carlomazzaferro/scikit-hts#17]
Carlo,

I have historical data which has both seasonal and linear components (e.g. sales that are both increasing month on month, and also have seasonal variations). Does the HTSregressor handle it? I am getting all negative forecasts when I tried your function. I have a hierarchy of 14 countries and 12 products under each country. I used Sarimax with revision method = 'OLS'.. Should I be using some other revision method?

Vasuki

Carlo, I was able to get rid of the negative values. But only problem is that forecast is flat even though the historical data has obvious linear trends and seasonal trends. Do we need to pass on some values to the underlying model (e.g. auto_arima, hot_winters). If so, how do you pass on those values though HTSRegressor?

Vasuki

**Comment by carlomazzaferro** [comment]
The revision method does not impact how the underlying forecasts are produced. To capture seasonal and trend components more easily, prophet is the way to go. I'd suggest you try fitting a single time series for it, and ensuring it captures your trend and seasonality.

Alternatively, auto_arima is also a good chioce, though fitting times might be slower. Once you found a model with parameters that make sense for your use-case, you can pass those parameters to HTSRegressor.fit(). Any kwarg will be passed down to the underlying method.
