### ISSUE TITLE
Parallelize fits

### ISSUE THREAD

**Issue by carlomazzaferro** [carlomazzaferro/scikit-hts#2]
Since each of the underlying models are constructed independently, offer the possibility to fit them in parallel.

Possible implementations:
 
1. Barebones python multiprocessing
2. joblib parallel

**Comment by ayushpatidar** [comment]
Hey we can use dask. A scalable library and very easy to integrate.

**Comment by carlomazzaferro** [comment]
I wouldn't want to add Dask as dependency if this can be solved using either built-ins or other light weight solutions. 

That being said, what benefits would Dask provide, and do you have a proposed implementation?

**Comment by ayushpatidar** [comment]
As the number of time series model trained to be trained gets large. There would be problem of load balancing and task failures. Which is quite easily handled by dask. 

And as i said earlier dask is very easy to integrate, as it is written in python itself.

**Comment by carlomazzaferro** [comment]
@ayushpatidar I'll look into that, closing here in favor of #7 , we can track progress there. I'm not too familiar with Dask so any inputs/proposed implementations are welcome
