### ISSUE TITLE
[BUG] UserWarning coming from predict in auto_arima

### ISSUE THREAD

**Issue by vtoliveira** [carlomazzaferro/scikit-hts#21]
**Describe the bug**
When fitting models using auto_arima, in prediction time a UserWarning for each node is logged into the screen.

![image](https://user-images.githubusercontent.com/32197310/81486569-fe8b1c00-922b-11ea-90de-beb09294590a.png)

**To Reproduce**
Fit a HTSRegressor using auto_arima a model option.

**Expected behavior**
No warning.

**Desktop (please complete the following information):**
 - OS: WSL
 - scikit-hts version: 0.5.1
- Python version:3.7.4

**Additional context**
I am not sure if this fits into a bug template of issues, please, tell me if it is more appropriate another tag.

**Comment by carlomazzaferro** [comment]
That's fine for now, though it seems like there isn't much we can do apart from migrating to newer versions of pmdarima. Feel free to test out different versions and check if it resolves the issue
