### ISSUE TITLE
[BUG] WLSS and WLSV are treated the sames as OLS by revise

### ISSUE THREAD

**Issue by ryanvolpi** [carlomazzaferro/scikit-hts#22]
**Describe the bug**
Revise method in revision.py treats WLSS and WLSV as OLS

**To Reproduce**
Specify the reconciliation method as WLSS or WLSV when using the hts regressor. 

**Expected behavior**
When self.name is OLS, WLSS, or WLSV, I would expect the revise method to pass method = self.name to optimal_combination() but instead, it passes method=MethodsT.OLS.name

**Desktop (please complete the following information):**
 - OS: Windows 10
 - scikit-hts version: [e.g. 0.2.1]
- Python version: 3.7.1

**Additional context**

**Comment by carlomazzaferro** [comment]
Thanks for spotting that! Quite a mistake; We'll have to work on verifying the tests for the WLSS and WLSV methods. I'll give it a look around Thursday this week.

**Comment by ryanvolpi** [comment]
Thanks! I took a look at the WLSS and WLSV methods but I haven't quite figured out the issue yet. I did notice that the WLSS method seems to be missing the kh values (the variances). I'll have time to figure it out on Friday.

**Comment by ryanvolpi** [comment]
I haven't been able to run the tests myself yet but the results on Github indicate that one of the revise methods encounters a singular matrix when computing the inverse. I don't know if this is a limitation of the method on the particular dataset or a problem with the implementation. The WLSS and WLSV methods seem to work fine on the Visnights dataset. However, WLSS estimates are wildly inaccurate, possibly because of the issue I mentioned above re the absence of Kh.

**Comment by ryanvolpi** [comment]
Nix that. Including the variance ultimately doesn't affect the results.

**Comment by carlomazzaferro** [comment]
@ryanvolpi feel free to change the test dataset and use the Visnights in the PR, which is realistically a more reasonable dataset than the currently used one (synthetic hierarchical sinusoidal data, an idea that I just came up with but that does not necessarily translate to real-world scenarios). Let me know if you can get around testing that, else I can give it a go.
