### ISSUE TITLE
[FEATURE] Add option for method = "NONE"

### ISSUE THREAD

**Issue by ryanvolpi** [carlomazzaferro/scikit-hts#24]
**Is your feature request related to a problem? Please describe.**
There is currently no way to compare the revised predictions against unrevised predictions. 

**Describe the solution you'd like**
An option to specify that the HTSRegressor applies no revision method and simply provides the predictions made by the individual models at each level. 

**Describe alternatives you've considered**

**Additional context**
I've implemented the feature very simply by adding the option in RevisionMethod.revise to return y_hat_matrix(forecasts = forecasts) when the method is NONE. Once I figure out how to correctly run the tests, I can submit a pull request if you think this is a worthwhile feature.

**Comment by carlomazzaferro** [comment]
Absolutely @ryanvolpi , fee free to send over the PR whenever you're ready!
