### ISSUE TITLE
unsupported operand type(s) for +: 'Timestamp' and 'NoneType' when using model.predict

### ISSUE THREAD

**Issue by matt-mrf** [carlomazzaferro/scikit-hts#30]
**Describe the bug**
After fitting the model, using model.predict(steps_ahead=n), it goes to 100% but then throws the following error: "unsupported operand type(s) for +: 'Timestamp' and 'NoneType' when using model.predict"

**To Reproduce**
I have a dataframe very similarly set up to the M5 notebook. I can't see any things in how it would
differ besides the numbers. The hierarchy is set up correctly.

**Expected behavior**
model.predict() should finish without errors.

**Desktop (please complete the following information):**
 - OS: OS X Catalina
 - scikit-hts version: 0.5.1
- Python version: 3.7.6

**Additional context**
I don't know exactly how predict works, so it seems it wants to use the index (datetime) and predict the next step..?

**Comment by vtoliveira** [comment]
Have you tried to transform your index in a datetime format? I have had similar issues, and solved that by doing, for example:

```python
df.index = pd.to_datetime(df.index)
```

**Comment by vtoliveira** [comment]
Look at this: https://github.com/carlomazzaferro/scikit-hts/issues/20

@carlomazzaferro can you think in something to deal to deal with that? Maybe an error instead of warning...

**Comment by matt-mrf** [comment]
> Have you tried to transform your index in a datetime format? I have had similar issues, and solved that by doing, for example:
> 
> ```python
> df.index = pd.to_datetime(df.index)
> ```

`df.index` gives me datetime already.. But using 

```python
> df.index = pd.to_datetime(df.index)
> ```

Did change something in the 

```
from hts.hierarchy import HierarchyTree

ht = HierarchyTree.from_nodes(nodes=hierarchy, df=df)
```

part of the code. I skipped using to datetime until after this step. I will let know if it changed anything after fitting. Thanks!

**Comment by matt-mrf** [comment]
`df.index = pd.to_datetime(df.index)` Did not work.. It throws the same initial error on predict.

**Comment by vtoliveira** [comment]
Give me the whole trace error, please.

**Comment by matt-mrf** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-325-93b9209cddb0> in <module>
----> 1 preds = model.predict()

~/anaconda3/envs/thesis/lib/python3.7/site-packages/hts/core/regressor.py in predict(self, exogenous_df, steps_ahead, distributor, disable_progressbar, show_warnings, **predict_kwargs)
    292             self.hts_result.errors = (key, error)
    293             self.hts_result.residuals = (key, residual)
--> 294         return self._revise(steps_ahead=steps_ahead)
    295 
    296     def _revise(self, steps_ahead=1):

~/anaconda3/envs/thesis/lib/python3.7/site-packages/hts/core/regressor.py in _revise(self, steps_ahead)
    303 
    304         revised_columns = list(make_iterable(self.nodes))
--> 305         revised_index = self._get_predict_index(steps_ahead=steps_ahead)
    306         return pandas.DataFrame(revised,
    307                                 index=revised_index,

~/anaconda3/envs/thesis/lib/python3.7/site-packages/hts/core/regressor.py in _get_predict_index(self, steps_ahead)
    311 
    312         freq = getattr(self.nodes.item.index, 'freq', 1)
--> 313         start = self.nodes.item.index[-1] + freq
    314         end = self.nodes.item.index[-1] + (steps_ahead * freq)
    315 

TypeError: unsupported operand type(s) for +: 'Timestamp' and 'NoneType'

**Comment by vtoliveira** [comment]
Try to do a resample in your dataframe. Something like:

```python
df = df.resample("D").sum()
```

We will need to fix that, but when datetime does not have a freq, it raises this error.

**Comment by matt-mrf** [comment]
That did the trick!

**Comment by vtoliveira** [comment]
You are welcome. I will try to see how they do that in statsmodels so we can replicate here, this is definitely a bug we should fix as soon as possible.

**Comment by ryanvolpi** [comment]
Are we considering adding support for numeric/ other types of indexes?

**Comment by 1653106** [comment]
You need to define the freq for your DatetimeIndex and it should be fine like below or df.index.freq = 'D' (or any type you want). If not its freq will be None and trigger this error!

> Try to do a resample in your dataframe. Something like:
> 
> ```python
> df = df.resample("D").sum()
> ```
> 
> We will need to fix that, but when datetime does not have a freq, it raises this error.

**Comment by vtoliveira** [comment]
I am not sure @ryanvolpi. To be honest, we could try pass predict to the underlying objects and they handle that better than us. I notice we are duplicating code in this matter and all tests related are going to be equal the ones in statsmodels. test_freq, test_predict_with_freq_D, etc. What do you think?
