### ISSUE TITLE
Cannot build hierarchy with large dataset

### ISSUE THREAD

**Issue by 1653106** [carlomazzaferro/scikit-hts#31]
* scikit-hts version: 0.5.1
* Python version: 3.7
* Operating System: Windows 10

### Description

Jupyter notebook's kernel is dead when trying to build HierarchyTree with a very large dataset.

### What I Did
My dataframe has 64 rows x  205664 columns. After building nodes I proceed to build the tree (I want to make sure before fitting it). I use Jupyter notebook. It runs for some time and the kernel is dead. Then I restart and run again, the kernel dies every time it reaches this part.
Maybe my tree is really deep and the leaves are really wide.

**To reproduce**
Build a hierarchy tree with a really large dataset.

**Expected behavior**
Tree is successfully built.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by carlomazzaferro** [comment]
Thanks for reporting. While I don't have a solution for you right now, it is good to know what kind of performance issues might arise when dealing with larger datasets. Just to give some background, the hierarchy tree is build by keeping in memory each node (represented as a pandas series/dataframe (in case you add exogenous variables)). 

In the future, it might be possible to defer the instantiation of the series until the fit procedure is called, so I'll add an issue for that use-case.
