### ISSUE TITLE
[BUG] Predict function fails when using the revision methods 'AHP' and 'PHA' while also setting transform=True

### ISSUE THREAD

**Issue by diggs1711** [carlomazzaferro/scikit-hts#33]
**Describe the bug**
The predict function of  a HTSRegressor throws the error ''bool' object has no attribute 'inverse_transform' when it is called with the revision method 'AHP' or 'PHA' and transform is set to True.

When the revision method is instantiated inside the _init_revision function, self.transform, which is a boolean value, is passed to the RevisionMethod class but it is expecting a transformer function to be passed. This causes the revision methods 'AHP' and 'PHA' to throw an error when the revise method from revision.py is called, as they try to use the inverse transform function.

**To Reproduce**
Create a HTSRegressor, setting the revision method to either 'AHP' or 'PHA' and set transform to True. Fit the model to data and then call the predict function.

**Expected behavior**
The predict function runs without error and outputs the correct predictions

**Desktop (please complete the following information):**
 N/A

**Additional context**
This was run on the free version of colab

**Comment by carlomazzaferro** [comment]
https://github.com/carlomazzaferro/scikit-hts/issues/38#issuecomment-853601578

**Comment by carlomazzaferro** [comment]
Merged: https://github.com/carlomazzaferro/scikit-hts/pull/72. Bump to 0.5.8 for new goodies. Make sure to read the docs on how to specify the transform: https://scikit-hts.readthedocs.io/en/latest/hts.html#hts.HTSRegressor.__init__
