### ISSUE TITLE
[BUG] BU revision seems have some bugs

### ISSUE THREAD

**Issue by svjack** [carlomazzaferro/scikit-hts#35]
**Describe the bug**

class method _y_hat_matrix seems like filter out 
leaves part of forecasts, but use keys generated by range
as int, so when call y_hat_matrix in functions.py will yield error
of can’t find key, because the key of forecasts may be str from 
df column names.  

**Additional context**
to tackle it. should resort the key to make root key in the first (the order is 
important) and perform simple edit.

**Comment by svjack** [comment]
may could overload _y_hat_matrix in this simple way:
`from hts.revision import *
class RevisionMethod_BU(RevisionMethod):
    def _y_hat_matrix(self, forecasts):
        print("forecasts first key: {}".format(list(forecasts.keys())[0]))
        n_cols = len(list(forecasts.keys())) + 1
        keys = range(n_cols - self.sum_mat.shape[1] - 1, n_cols - 1)
        named_keys = list(map(lambda k_idx: list(forecasts.keys())[k_idx], keys))
        return y_hat_matrix(forecasts, keys=named_keys) `

**Comment by svjack** [comment]
![Uploading D89B2EA0-170D-4C82-988A-05D7614105A0.jpeg…]()
may edit _y_mat_matrix of RevisionMethod

**Comment by svjack** [comment]
![Uploading 9F67154F-2F2B-4F21-A3B5-0CBF5EACBB9D.jpeg…]()

**Comment by svjack** [comment]
![Uploading 88894415...]()

**Comment by carlomazzaferro** [comment]
Thanks for the report. Would you be interested in submitting a PR? @svjack

**Comment by svjack** [comment]
> Thanks for the report. Would you be interested in submitting a PR? @svjack
this may help.
https://github.com/svjack/Bu-Hts

**Comment by JustinNeumann** [comment]
+1

**Comment by javierhuertay** [comment]
> 
> 
> +1 but solved it, let me know if you like a PR for this one. Basically I changed **_y_hat_matrix** in **revision.py** to overwrite **keys** in case of BU chosen.
> 
> if self.name == MethodsT.BU.name:
> keys = list(forecasts.keys())[n_cols - self.sum_mat.shape[1] - 1:n_cols - 1]

Thank you Justin,
Don't know what **MethodsT.BU.name**, but in my case in with == 'BU' worked.

@carlomazzaferro I think that this must be a PR, there are many people getting the same error.

Like, https://towardsdatascience.com/introduction-to-hierarchical-time-series-forecasting-part-ii-e73dfd3de86b

**Comment by carlomazzaferro** [comment]
> > 
> > 
> > +1 but solved it, let me know if you like a PR for this one. Basically I changed **_y_hat_matrix** in **revision.py** to overwrite **keys** in case of BU chosen.
> > 
> > if self.name == MethodsT.BU.name:
> > keys = list(forecasts.keys())[n_cols - self.sum_mat.shape[1] - 1:n_cols - 1]
> 
> Thank you Justin,
> Don't know what **MethodsT.BU.name**, but in my case in with == **'BU' worked**.
> 
> @carlomazzaferro I think that this must be a PR, there are many people getting the same error.
> 
> Like, https://towardsdatascience.com/introduction-to-hierarchical-time-series-forecasting-part-ii-e73dfd3de86b

Thanks for bumping this -- somehow missed it. Let me know if you want to PR it, else I'll try to get it this weekend

**Comment by javierhuertay** [comment]
> 
> 
> > > +1 but solved it, let me know if you like a PR for this one. Basically I changed **_y_hat_matrix** in **revision.py** to overwrite **keys** in case of BU chosen.
> > > if self.name == MethodsT.BU.name:
> > > keys = list(forecasts.keys())[n_cols - self.sum_mat.shape[1] - 1:n_cols - 1]
> > 
> > 
> > Thank you Justin,
> > Don't know what **MethodsT.BU.name**, but in my case in with == **'BU' worked**.
> > @carlomazzaferro I think that this must be a PR, there are many people getting the same error.
> > Like, https://towardsdatascience.com/introduction-to-hierarchical-time-series-forecasting-part-ii-e73dfd3de86b
> 
> Thanks for bumping this -- somehow missed it. Let me know if you want to PR it, else I'll try to get it next week

I tried but I'm unable to run python setup.py test, it says **error: invalid command 'pytest'**

**Comment by carlomazzaferro** [comment]
This should be added to the docs -- I'll provide a patch.

Linting:
```
black --check . && isort --check --profile black .
```

Testing:
```
pip install -r reqs/test.txt
```

**Comment by carlomazzaferro** [comment]
Closed via https://github.com/carlomazzaferro/scikit-hts/pull/63
