### ISSUE TITLE
[BUG] Bug report

### ISSUE THREAD

**Issue by ashkrelja** [carlomazzaferro/scikit-hts#37]
**Describe the bug**
Cannot import name 'HierarchyTree' from 'hts

**To Reproduce**
from hts import HierarchyTree

**Expected behavior**
Expected HierarchyTree to be imported in order to define a hierarchy to pass into HTSRegressor.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - scikit-hts version: 0.5.2
- Python version: 3.7.3

**Additional context**

ImportError: cannot import name 'HierarchyTree' from 'hts' (C:\Users\Private\AppData\Local\Continuum\anaconda3\lib\site-packages\hts\__init__.py)

**Comment by carlomazzaferro** [comment]
Update to 0.5.3
