### ISSUE TITLE
[BUG] Boxcox transform fails for a Prophet model

### ISSUE THREAD

**Issue by jstammers** [carlomazzaferro/scikit-hts#38]
**Describe the bug**
I am unable to obtain predictions from a `FBProphetModel` when `transform=True`. 
The error message implies that it is unable to safely apply the `inv_boxcox` method to the values returned by the `Prophet` model.
I suspect this is because the model is returning negative values. 
**To Reproduce**
```python
from hts import HTSRegressor
from hts.utilities.load_data import load_mobility_data
df = load_mobility_data()
hier = {
        'total': ['CH', 'SLU', 'BT', 'OTHER'],
        'CH': ['CH-07', 'CH-02', 'CH-08', 'CH-05', 'CH-01'],
        'SLU': ['SLU-15', 'SLU-01', 'SLU-19', 'SLU-07', 'SLU-02'],
        'BT': ['BT-01', 'BT-03'],
        'OTHER': ['WF-01', 'CBD-13']
    }
reg = HTSRegressor(model='prophet', transform=True)
reg = reg.fit(df=df, nodes=hier)
reg.predict(num_steps=30)
Traceback:
...
TypeError: ufunc 'inv_boxcox' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Expected behavior**
When calling the underlying Prophet model, the input data should be transformed to ensure that the predicted values are positive

**Desktop (please complete the following information):**
 - OS: Linux arch-5.5.7
 - scikit-hts version: 0.5.1
- Python version: 3.7.6

**Additional context**
I've tried forcing prophet to fit to positive values using
```python
reg = HTSRegressor(model='prophet', capacity_min=0, capacity_max=10000)
reg.fit(df, nodes=hier)
reg.predict(steps_ahead=30)
```
which fails because the underlying dataframes have no 'cap' value.

**Comment by edarca** [comment]
I am unable too. I have tried to transform the negatives values, but still appears same error. Do anyone know why it happens?
Have you found a solution @jstammers ?

**Comment by jeremydiba** [comment]
Also Encountering this bug

**Comment by JustinNeumann** [comment]
+1

**Comment by carlomazzaferro** [comment]
The transform is finnicky, and  likely one of the least tested portions of the codebase. I'll be revamping it in the coming days.

**Comment by cdeterman** [comment]
Upvote, I am encountering this same continued issue.

**Comment by carlomazzaferro** [comment]
Thanks all for keeping me on my toes. WIP: https://github.com/carlomazzaferro/scikit-hts/pull/72

**Comment by carlomazzaferro** [comment]
Merged: https://github.com/carlomazzaferro/scikit-hts/pull/72. Bump to 0.5.8 for new goodies. Make sure to read the docs on how to specify the transform: https://scikit-hts.readthedocs.io/en/latest/hts.html#hts.HTSRegressor.__init__
