### ISSUE TITLE
[ENHANCEMENT] Add support for other python versions / platforms 

### ISSUE THREAD

**Issue by carlomazzaferro** [carlomazzaferro/scikit-hts#4]
**Is your proposed enhancement related to a problem? Please describe.**
Add support and automated tests for python 3.5+, and for MacOS, Windows

**Describe the solution you'd like**
Add test matrix with tox

**Describe alternatives you've considered**
Tox, or any other solution that would run tests on travis ci for dfferent versions/platforms

**Comment by noahsa** [comment]
In progress #71
