### ISSUE TITLE
[BUG] Getting Error Message when Using the Package to Predict

### ISSUE THREAD

**Issue by rosie-grq** [carlomazzaferro/scikit-hts#41]
**Describe the bug**
The following error message comes from the predict function:
<img width="999" alt="Screen Shot 2020-08-29 at 1 31 17 PM" src="https://user-images.githubusercontent.com/58502892/91645737-9049af80-e9fc-11ea-8c3f-6cda4afc7b28.png">

**To Reproduce**
Input:
<img width="969" alt="Screen Shot 2020-08-29 at 1 32 51 PM" src="https://user-images.githubusercontent.com/58502892/91645739-9770bd80-e9fc-11ea-8231-7ba220bcdb37.png">

The type of index is string, store columns with a total column in the dataframe
Tried to convert the index to datetime, but getting another error message for incompatibility of timestamp and object

Code:
clf = HTSRegressor(model='prophet', revision_method='OLS', n_jobs=12)
model = clf.fit(hts_ssm, hier)
preds = model.predict(steps_ahead=2,freq='M')

also tried freq='D' but getting the same error. 

**Expected behavior**
Expected not getting an error.

**Desktop (please complete the following information):**
 - OS: [OS X Catalina]
 - scikit-hts version: [0.2.1]
- Python version: [ 3.7.4]

**Additional context**

**Comment by laurademenezes** [comment]
I solved it by making sure the index is in datetime format and also changing the original _get_predict_index function on regressor.py file to this code below

`def _get_predict_index(self, steps_ahead=1):

        freq = getattr(self.nodes.item.index, 'freq', 1)
        start = self.nodes.item.index[-1]

        future = pandas.date_range(freq='MS',
                                   start=start,
                                   periods=steps_ahead
                                   )

        return self.nodes.item.index.append(future.to_pydatetime().tolist())`
