### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by ghrahul** [carlomazzaferro/scikit-hts#42]
**ValueError**
ValueError: shapes (533,533) and (505,) not aligned: 533 (dim 1) != 505 (dim 0)

The shape of my modeling data frame is 42 rows × 505 columns. 

```
clf = HTSRegressor(model='prophet', revision_method='OLS', n_jobs=12)
model = clf.fit(model_df, hierarchy)
```
The fit function is working fine and doing the 100% training. But when I am doing 
```
preds = model.predict(steps_ahead=3)
```
I am getting value error after the 100% training is done. I have printed each step I am getting output till new_mat and hat_mat

```
def project(hat_mat: np.ndarray, sum_mat: np.ndarray, optimal_mat: np.ndarray) -> np.ndarray:
    new_mat = np.empty([hat_mat.shape[0], sum_mat.shape[0]])
    print(f"hat_mat: {hat_mat}")
    for i in range(hat_mat.shape[0]):
        new_mat[i, :] = np.dot(optimal_mat, np.transpose(hat_mat[i, :]))
    return new_mat
```

**Comment by ghrahul** [comment]
I further found out that for the example from scikit-hts-examples the M5 notebook is working fine and for the modelling data frame of shape 1913 rows × 30604 columns, the following function is generating sum_mat shape 30604, 30490
```
def to_sum_mat(ntree: NAryTreeT):
    """
    This function creates a summing matrix for the bottom up and optimal combination approaches
    All the inputs are the same as above
    The output is a summing matrix, see Rob Hyndman's "Forecasting: principles and practice" Section 9.4

    Parameters
    ----------
    ntree : NAryTreeT


    Returns
    -------

    """

    #TODO this needs to be changed
    print(f"************sum matrix********")
    nodes = ntree.level_order_traversal()
    num_at_level = list(map(sum, nodes))
    columns = num_at_level[-1]
    bl_mat = np.identity(columns)
    top = np.ones(columns)
    final_mat = bl_mat
    num_levels = len(num_at_level)
    print(f"nodes: {nodes}, num_at_level: {num_at_level}, columns: {columns}, bl_mat_shape: {bl_mat.shape}, top: {top.shape}, final_mat: {final_mat.shape}, num_levels: {num_levels}")

    for lev in range(num_levels - 1):
        summing = nodes[-(lev + 1)]
        count = 0
        num2sum_ind = 0
        B = np.zeros([num_at_level[-1]])
        for num2sum in summing:
            num2sum_ind += num2sum
            a = bl_mat[count:num2sum_ind, :]
            count += num2sum
            if np.all(B == 0):
                B = a.sum(axis=0)
            else:
                B = np.vstack((B, a.sum(axis=0)))
        final_mat = np.vstack((B, final_mat))
        bl_mat = B

    final_mat = np.vstack((top, final_mat))
    print(f"final_mat from sum_mat: {final_mat.shape}")
    return final_mat
```
But in my case, it is adding 28 extra rows which are causing the problem.

**Comment by ghrahul** [comment]
The hierarchy tree cannot have the same name child for different nodes.

**Comment by ghrahul** [comment]
The hierarchy tree cannot have the same name child for different nodes.

**Comment by r4ch45** [comment]
Hi There,
I think I have a similar error, but don't quite understand your solution, or if it indeed is the same thing. Appreciate any insight!

My hierachy:
- TED
   |- GT
   |- WIND
   - ALL_BUT_WIND_AND_GT
      |- COAL
      |- NUCLEAR
      |- REST
      |- BIOMASS
      - INTERCONNECTORS

Initial fit is fine, but when I come to predict I get a ValueError from mismatched arrays. If I reduce the hierarchy back to one layer, then I don't have this issue...
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-120-de709f2783ed> in <module>
----> 1 predicted_autoarima = model.predict(steps_ahead=1)

~\.conda\envs\TS\lib\site-packages\hts\core\regressor.py in predict(self, exogenous_df, steps_ahead, distributor, disable_progressbar, show_warnings, **predict_kwargs)
    292             self.hts_result.errors = (key, error)
    293             self.hts_result.residuals = (key, residual)
--> 294         return self._revise(steps_ahead=steps_ahead)
    295 
    296     def _revise(self, steps_ahead=1):

~\.conda\envs\TS\lib\site-packages\hts\core\regressor.py in _revise(self, steps_ahead)
    296     def _revise(self, steps_ahead=1):
    297         logger.info(f'Reconciling forecasts using {self.revision_method}')
--> 298         revised = self.revision_method.revise(
    299             forecasts=self.hts_result.forecasts,
    300             mse=self.hts_result.errors,

~\.conda\envs\TS\lib\site-packages\hts\revision.py in revise(self, forecasts, mse, nodes)
     47 
     48         if self.name in [MethodsT.OLS.name, MethodsT.WLSS.name, MethodsT.WLSV.name]:
---> 49             return optimal_combination(forecasts=forecasts,
     50                                        sum_mat=self.sum_mat,
     51                                        method=self.name,

~\.conda\envs\TS\lib\site-packages\hts\functions.py in optimal_combination(forecasts, sum_mat, method, mse)
    105     if method == MethodsT.OLS.name:
    106         ols = np.dot(np.dot(sum_mat, np.linalg.inv(np.dot(transpose, sum_mat))), transpose)
--> 107         return project(hat_mat=hat_mat, sum_mat=sum_mat, optimal_mat=ols)
    108     elif method == MethodsT.WLSS.name:
    109         diag = np.diag(np.transpose(np.sum(sum_mat, axis=1)))

~\.conda\envs\TS\lib\site-packages\hts\functions.py in project(hat_mat, sum_mat, optimal_mat)
     55     new_mat = np.empty([hat_mat.shape[0], sum_mat.shape[0]])
     56     for i in range(hat_mat.shape[0]):
---> 57         new_mat[i, :] = np.dot(optimal_mat, np.transpose(hat_mat[i, :]))
     58     return new_mat
     59 

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: shapes (7,7) and (9,) not aligned: 7 (dim 1) != 9 (dim 0)`

**Comment by andreluis-p** [comment]
I also couldn’t understand the solution… my error is exactly the same… I would highly appreciate a more detailed solution… thanks a lot. :)

**Comment by bentontripp** [comment]
I am still getting this error, and am unable to find a solution. Has anybody else been able to solve this issue? Like it was mentioned in previous comments, the explanation doesn't really make sense... and thus far, everything I have attempted has been fruitless.

**Comment by nehcgnak** [comment]
> I also couldn’t understand the solution… my error is exactly the same… I would highly appreciate a more detailed solution… thanks a lot. :)

Do you figure out how to solve it? I have the similar issue shown below when the method=BU.
shapes (204,190) and (187,) not aligned: 190 (dim 1) != 187 (dim 0)
The 190 represents the # of bottom level components, I checked my tree and it does have 190 components at the bottom level but the weird thing is when it reconciliates the # decreases to 187. I don't know how to fix it. All my node names are unique. And the code works well with other methods.

**Comment by nehcgnak** [comment]
> The hierarchy tree cannot have the same name child for different nodes.

All my node names are unique. The issue of my code is that it somehow decreases the # of bottom level components during the reconciliation and the error message comes out. However, when I print out the # of bottom level components from the "tree", the # is the same as the column # of the summing matrix.
