### ISSUE TITLE
[BUG] Bug report: AttributeError: 'NoneType' object has no attribute 'fit'.

### ISSUE THREAD

**Issue by pankaj-kvhld** [carlomazzaferro/scikit-hts#49]
**Bug description**
While trying to reproduce the example given here: https://scikit-hts.readthedocs.io/en/latest/usage.html, I got the following error.  Same error appears when running https://github.com/carlomazzaferro/scikit-hts-examples/blob/master/notebooks/visnights.ipynb too. 

**To Reproduce**
```
from hts import HTSRegressor
from hts.utilities.load_data import load_hierarchical_sine_data
from datetime import datetime

# load some data
s, e = datetime(2019, 1, 15), datetime(2019, 10, 15)
df = load_hierarchical_sine_data(s, e).resample('1H').apply(sum)

hier = {
    "total": ["a", "b", "c"],
    "a": ["aa", "ab"],
    "aa": ["aaa", "aab"],
    "b": ["ba", "bb"],
    "c": ["ca", "cb", "cc", "cd"],
}

reg = HTSRegressor(model='prophet', revision_method='OLS')
reg = reg.fit(df=df, nodes=hier)
```

**Throws the following error**
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\rft\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\joshipan\downloads\scikit-hts\hts\utilities\distribution.py", line 40, in _function_with_partly_reduce
    return list(results)
  File "c:\users\joshipan\downloads\scikit-hts\hts\utilities\distribution.py", line 39, in <genexpr>
    results = (map_function(chunk, kwargs) for chunk in chunk_list)
  File "c:\users\joshipan\downloads\scikit-hts\hts\core\utils.py", line 39, in _do_actual_fit
    model_instance = instantiated_model.fit(**function_kwargs['fit_kwargs'])
  File "c:\users\joshipan\downloads\scikit-hts\hts\model\p.py", line 87, in fit
    self.model = self.model.fit(df)
AttributeError: 'NoneType' object has no attribute 'fit'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-1-33b10c6af900> in <module>()
     16 
     17 reg = HTSRegressor(model='prophet', revision_method='OLS')
---> 18 reg = reg.fit(df=df, nodes=hier)

c:\users\joshipan\downloads\scikit-hts\hts\core\regressor.py in fit(self, df, nodes, tree, exogenous, root, distributor, disable_progressbar, show_warnings, **fit_kwargs)
    211             n_jobs=self.n_jobs,
    212             disable_progressbar=disable_progressbar, show_warnings=show_warnings,
--> 213             distributor=distributor
    214         )
    215 

c:\users\joshipan\downloads\scikit-hts\hts\core\utils.py in _do_fit(nodes, function_kwargs, n_jobs, disable_progressbar, show_warnings, distributor)
     25     result = distributor.map_reduce(_do_actual_fit,
     26                                     data=nodes,
---> 27                                     function_kwargs=function_kwargs)
     28     distributor.close()
     29     return result

c:\users\joshipan\downloads\scikit-hts\hts\utilities\distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    164                       disable=self.disable_progressbar)
    165 
--> 166         result = list(itertools.chain.from_iterable(result))
    167 
    168         return result

C:\ProgramData\Anaconda3\envs\rft\lib\site-packages\tqdm\std.py in __iter__(self)
   1106                 fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1107 
-> 1108         for obj in iterable:
   1109             yield obj
   1110             # Update and possibly print the progressbar.

C:\ProgramData\Anaconda3\envs\rft\lib\multiprocessing\pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

AttributeError: 'NoneType' object has no attribute 'fit'

**Desktop:**
 - OS: [e.g. Windows 10, 64 bit]
 - scikit-hts version: 0.5.2
 - scikit-learn 0.23.2
- Python version:  3.6.12

**Comment by carlomazzaferro** [comment]
Can't reproduce, might be related to how the implementation of multiprocessing works on Windows. Note Windows is not currently supported / tested. 

A few notes: 
- Bump scikit-hts version to 0.5.3, as it has some improvements in how parallelism is handled
- Try running the examples in docker, with `docker run carlomazzaferro/scikit-hts-examples:0.2.2`

**Comment by mtorabirad** [comment]
I get the same error: "AttributeError: 'NoneType' object has no attribute 'fit'"
