### ISSUE TITLE
[DOCS] Documentation Example of how to apply top-down, middle-out, bottom-up approach.

### ISSUE THREAD

**Issue by an5ir** [carlomazzaferro/scikit-hts#50]
Hi, 

In the fpp2 book on the chapter  [Forecasting hierarchical or grouped time series](https://otexts.com/fpp2/bottom-up.html), it is possible to easily switch between different methods (top-down, middle-out, bottom-up) when using the hts approach.

```
prison.gts <- gts(prison/1e3, characters = c(3,1,9),
  gnames = c("State", "Gender", "Legal",
             "State*Gender", "State*Legal",
             "Gender*Legal"))
forecast(prison.gts, method="bu", fmethod="arima")
```

can you provide an example of how this can be done using scikit-hts package

**Comment by carlomazzaferro** [comment]
https://scikit-hts.readthedocs.io/en/latest/hts.html#hts.HTSRegressor.__init__

You can see which approaches are available here

**Comment by PeggyFan** [comment]
@carlomazzaferro Is bottom-up the only available approach? I do not see anything explicit but I found the function ```forecast_proportions``` to be a possible candidate for the Top-Down approach? But how can I use this function to perform this approach?
