### ISSUE TITLE
[DOCS] Seasonality Mode for Prophet?

### ISSUE THREAD

**Issue by cdeterman** [carlomazzaferro/scikit-hts#52]
I don’t know if I am overlooking it but is there a way to specify multiplicative seasonality for the underlying prophet models?

for details see here https://facebook.github.io/prophet/docs/multiplicative_seasonality.html

**Comment by carlomazzaferro** [comment]
That is possible. You can pass prophet specific params to the model instantiation via the `HTSRgressor`'s kwargs. They will be transparently passed to the instantiation of the `fbprophet.Prophet` underlying models
