### ISSUE TITLE
[FEATURE] Automatic Generation of Hierarchy Dataset and Mapping

### ISSUE THREAD

**Issue by rohan-gt** [carlomazzaferro/scikit-hts#57]
**Is your feature request related to a problem? Please describe.**
It's very complex to create the hierarchical pivot dataset from a dataset in its long form especially if there are many levels in the hierarchy

**Describe the solution you'd like**
A method which takes in the date field and a list of levels (column names) in the dataset and generates the pivot table at the date level and the hierarchy mapping dictionary after learning the relationships from the dataset itself

**Describe alternatives you've considered**
Manually creating the dataset and dictionary which can be tedious and error prone

**Comment by carlomazzaferro** [comment]
This seems reasonable at a first glance -- to be sure, you'd like to have an automated way of going from [list of records ungrouped by either time or group] -> [grouped time series, indexed by time]. The inputs here would be the long-form data frame, as well as a dictionary mapping (likely having some sort of nesting to indicate parent-child relationship).

Is this correct? If you could provide a simple example, I think we can both benefit from that.

**Comment by carlomazzaferro** [comment]
If what I describe is what you need, this has been discussed in the past. See https://github.com/carlomazzaferro/scikit-hts/issues/15

The notebook linked, now in master, also does have a sample implementation (though specific to its data). I'd welcome you to suggest an implementation that can be placed in our `hts.utils` module. 

In the meantime, I'll close this one in favour of the more extensive https://github.com/carlomazzaferro/scikit-hts/issues/15
