### ISSUE TITLE
[BUG] How are time series of unequal lengths handled?

### ISSUE THREAD

**Issue by rohan-gt** [carlomazzaferro/scikit-hts#58]
Imagine that I'm trying to model multiple time series having different date ranges, meaning a lot of missing values when combined together. How are these time series modelled in this package?

**Comment by carlomazzaferro** [comment]
It is currently assumed by the package that the time series are all time-aligned. If the underlying time-series contain missing values, you'd have to either deal with them yourself, or assume that the underlying model deals with them natively (i.e.; you'd be offloading the functionality of dealing with missing values to prophet, AutoARIMA, etc.)
