### ISSUE TITLE
revise_forecasts() method raises an attribute error. AttributeError: 'Series' object has no attribute 'yhat'

### ISSUE THREAD

**Issue by aakashparsi** [carlomazzaferro/scikit-hts#65]
I want to revise my base forecasts, so wanted to use revise_forecasts() method but got an error like this. 

* scikit-hts version: scikit-hts==0.5.4
* Python version: 3.6
* Operating System: Windows

```
AttributeError                            Traceback (most recent call last)
<ipython-input-191-307987f74b26> in <module>
----> 1 revise_forecasts(method = 'FP', forecasts = pred, summing_matrix = sum_mat, nodes = hierarchyNodes)

/home/Gopal/anaconda/envs/time_series/lib/python3.6/site-packages/hts/convenience.py in revise_forecasts(method, forecasts, errors, residuals, summing_matrix, nodes, transformer)
     63     )
     64 
---> 65     revised = revision.revise(forecasts=forecasts, mse=errors, nodes=nodes)
     66 
     67     return pandas.DataFrame(revised, columns=list(forecasts.keys()))

/home/Gopal/anaconda/envs/time_series/lib/python3.6/site-packages/hts/revision.py in revise(self, forecasts, mse, nodes)
     74 
     75         elif self.name == MethodT.FP.name:
---> 76             return forecast_proportions(forecasts, nodes)
     77 
     78         else:

/home/Gopal/anaconda/envs/time_series/lib/python3.6/site-packages/hts/functions.py in forecast_proportions(forecasts, nodes)
    196 
    197     key = choice(list(forecasts.keys()))
--> 198     new_mat = np.empty([len(forecasts[key].yhat), n_cols - 1])
    199     new_mat[:, 0] = forecasts[key].yhat
    200 

/home/Gopal/anaconda/envs/time_series/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'yhat'
```

What could be the best fix for this problem?

**Comment by carlomazzaferro** [comment]
This was due to bad assumptions on the format of the `forecasts` dict. It was assumed that it is a DataFrame with a single columns, named `yhat`.

[This PR](https://github.com/carlomazzaferro/scikit-hts/pull/67) address it. Feel free to take a look, the tests should make it clear what the PR is achieving.

**Comment by aakashparsi** [comment]
Thanks for the update @carlomazzaferro. 
I just want to clarify one thing here. So, according to the updated code, To revise the forecasts we have to pass the DataFrame with one column. Is that right? If yes, then It would be better if you update the same in the documentation.

**Comment by aakashparsi** [comment]
And, the same error pops up when using optimal_combination().
Here is the stack trace
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-152-a556a14422e8> in <module>
----> 1 optimal_combination(dict(pred[-4:]), sum_mat = htsmodel.sum_mat, method = 'OLS', mse = {} )

~/.conda/envs/lts/lib/python3.6/site-packages/hts/functions.py in optimal_combination(forecasts, sum_mat, method, mse)
    128 
    129     """
--> 130     hat_mat = y_hat_matrix(forecasts)
    131     transpose = np.transpose(sum_mat)
    132 

~/.conda/envs/lts/lib/python3.6/site-packages/hts/functions.py in y_hat_matrix(forecasts, keys)
     89         keys = forecasts.keys()
     90     first = list(forecasts.keys())[0]
---> 91     y_hat_mat = np.zeros([len(forecasts[first].yhat), 1])
     92     for key in keys:
     93         f1 = np.array(forecasts[key].yhat)

~/.conda/envs/lts/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'yhat'
```

**Comment by carlomazzaferro** [comment]
You should not use `optimal_combination` directly. The new function that perform sanitization on the inputs should transform whatever you pass as your forecasts to a format that should work with the `revised = revision.revise(forecasts=forecasts, mse=errors, nodes=nodes)` (`optimal_combination` gets called by this method). 

Now, you should be able to pass as forecasts a dict of strings to either `numpy.array` (as long as the array has ndim == 1), `pandas.Series` or `pandas.DataFrame` (as long as the df has only one column). 

But I suggest you to wait till tomorrow, as I'm still working on some further fixes to the convenience methods. You can track the progress here: https://github.com/carlomazzaferro/scikit-hts/pull/68

**Comment by carlomazzaferro** [comment]
Feel free to bump to scikit-hts 0.5.6, see updated convenience docs https://scikit-hts.readthedocs.io/en/latest/hts.html#module-hts.convenience 

Thanks for your patience!

**Comment by aakashparsi** [comment]
Sure @carlomazzaferro. Also, It would be very helpful If you throw some light on #66.

**Comment by carlomazzaferro** [comment]
Yes, that is next on my task list and will tackle that together with the related issue about fixing the transforms functionality. Will keep posted when I have a PR in the works

**Comment by aakashparsi** [comment]
Sure @carlomazzaferro. I Wholeheartedly appreciate all your efforts on this. Thank you so much.
