### ISSUE TITLE
Still a bug in the current implementation of exogenous variables

### ISSUE THREAD

**Issue by wilfreddesert** [carlomazzaferro/scikit-hts#75]
https://github.com/carlomazzaferro/scikit-hts/blob/a191eb080d881a071812b539a5bf84f49c5043cd/hts/core/regressor.py#L271

This line results in:
`ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

I guess it should be `elif exogenous_df is not None` so that everything works.

**Comment by carlomazzaferro** [comment]
Good spotting, test case for that branch of the code is indeed missing. Wanna PR and and said test case? I'm out for the next few days

**Comment by wilfreddesert** [comment]
I am taking a look. But there is one strange thing. Running this `REPORT=False make test` yields a few failures. I followed the instructions precisely, but it seems that some of the existing tests fail even without any changes in the code on my side.

**Comment by wilfreddesert** [comment]
Probably, it was too naive of me to assume that having Python 3.9 doesn't matter :)

**Comment by carlomazzaferro** [comment]
Hey if you're into it, adding 3.9 support could be pretty cool 🙃. In fact we're trying to support the latest 3 python versions, and AFAICT 3.9 was released Oct 5 2020 so it would make sure to add that and deprecate 3.6. I'll file an issue for that

**Comment by wilfreddesert** [comment]
> Hey if you're into it, adding 3.9 support could be pretty cool . In fact we're trying to support the latest 3 python versions, and AFAICT 3.9 was released Oct 5 2020 so it would make sure to add that and deprecate 3.6. I'll file an issue for that

I would love too right after fixing the issues with exogenous variables. But now it seems that I am not able to run all tests successfully. Can you confirm that all of them run without errors on your side?

**Comment by wilfreddesert** [comment]
It feels like there is some sort of incompatibility between pystan, fbprophet and/or numpy. Trying to figure it out, but that is a bit strange given that all the package versions should match the requirements

**Comment by carlomazzaferro** [comment]
CI runs should confirm you that all the tests pass with 3.6, 3.7, 3.8 on
both Mac and  Linux. You're welcome to checkout master and follow the CI
workflow -- follow the set up steps and that should ensure you have the
right libs / env

**Comment by wilfreddesert** [comment]
You can take a look at my PR. It's not that good, but now it at least works the way I expect it to work when passing exogenous variables :)

**Comment by aakashparsi** [comment]
@wilfreddesert, @carlomazzaferro I have a query regarding exogenous variables. I have built a 3 level hierarchical structure(root, level1, level2). Leaving the root node, is it possible for me to add exogenous variables for all the nodes present in the remaining levels? I'm getting an error if I'm trying to do the same. Any insights on this?
