### ISSUE TITLE
[BUG] Probably a bug in how reconciliation works now 

### ISSUE THREAD

**Issue by wilfreddesert** [carlomazzaferro/scikit-hts#77]
**Describe the bug**
It seems that currently there is either a bug in how reconciliation works or probably I just don't quite understand how it works :) 

**To Reproduce**

```    def _y_hat_matrix(self, forecasts) -> numpy.ndarray:
        n_cols = len(list(forecasts.keys())) + 1
        if self.name == "BU":
            keys = list(forecasts.keys())[
                n_cols - self.sum_mat.shape[1] - 1 : n_cols - 1
            ]
        else:
            keys = range(n_cols - self.sum_mat.shape[1] - 1, n_cols - 1)
        return y_hat_matrix(forecasts, keys=keys)
 ```
 
 
**Expected behavior**
Surprisingly, in particular for the `BU` method some columns get removed from the dataframe and then the predicted dataframe has zeros instead of the forecasts. 

```
from hts import HTSRegressor
from hts.hierarchy import HierarchyTree
from hts.utilities.load_data import load_hierarchical_sine_data, load_mobility_data
data = load_mobility_data()
hier = {
    "total": ["CH", "SLU", "BT", "OTHER"],
    "CH": ["CH-07", "CH-02", "CH-08", "CH-05", "CH-01"],
    "SLU": ["SLU-15", "SLU-01", "SLU-19", "SLU-07", "SLU-02"],
    "BT": ["BT-01", "BT-03"],
    "OTHER": ["WF-01", "CBD-13"],
}
train = data[:500]
test = data[500:507]
clf = HTSRegressor(model="prophet", n_jobs=10)
exogenous = {
    k: ["precipitation", "temp"]
    for k in data.columns
    if k not in ["precipitation", "temp"]
}
model = clf.fit(train.drop(columns=["precipitation", "temp"]), hier)
preds = model.predict(steps_ahead=7)
```

Here is how you can reproduce the issue. 

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro)
 - scikit-hts version: 0.5.11
- Python version: 3.7.9

**Additional context**
It might be as well that I am missing something in the way it's supposed to work. I just noticed in the above example that the returned dataframe doesn't have correct predictions (for example, the column for `CH` has zeros everywhere). The issue arises prior to reconciliation: checking `self.hts_result.forecasts` confirms that the raw predictions are okay. 

@carlomazzaferro , can you please take a look?

**Comment by carlomazzaferro** [comment]
Needs investigation. Will look into this this week.

**Comment by noahsa** [comment]
I think this is tied to issue #78, where there are issues specifying the hierarchy with the mobility dataset.
