### ISSUE TITLE
[BUG] Error installing with pip install scikit-hts[all]

### ISSUE THREAD

**Issue by bobbyinfj** [carlomazzaferro/scikit-hts#82]
**Describe the bug**
Pip install with the all tag does not work.

```pip install scikit-hts[all]```
returns 
```no matches found: scikit-hts[all]```

**To Reproduce**

**Expected behavior**
Installation of all packages

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (m1 chip)
 - scikit-hts version: latest
- Python version: 3.8.11

**Additional context**

**Comment by carlomazzaferro** [comment]
```
 pip install "scikit-hts[all]"
```
